#include "glFunctions.h"

PFNGLACTIVETEXTUREPROC glActiveTexture;
PFNGLATTACHSHADERPROC glAttachShader;
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
PFNGLBINDBUFFERPROC glBindBuffer;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
PFNGLBINDTEXTUREPROC glBindTexture;
PFNGLBLENDCOLORPROC glBlendColor;
PFNGLBLENDEQUATIONPROC glBlendEquation;
PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;
PFNGLBLENDFUNCPROC glBlendFunc;
PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;
PFNGLBUFFERDATAPROC glBufferData;
PFNGLBUFFERSUBDATAPROC glBufferSubData;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
PFNGLCLEARPROC glClear;
PFNGLCLEARCOLORPROC glClearColor;
PFNGLCLEARDEPTHFPROC glClearDepth;
PFNGLCLEARSTENCILPROC glClearStencil;
PFNGLCOLORMASKPROC glColorMask;
PFNGLCOMPILESHADERPROC glCompileShader;
PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D;
PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D;
PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D;
PFNGLCREATEPROGRAMPROC glCreateProgram;
PFNGLCREATESHADERPROC glCreateShader;
PFNGLCULLFACEPROC glCullFace;
PFNGLDELETEBUFFERSPROC glDeleteBuffers;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
PFNGLDELETEPROGRAMPROC glDeleteProgram;
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
PFNGLDELETESHADERPROC glDeleteShader;
PFNGLDELETETEXTURESPROC glDeleteTextures;
PFNGLDEPTHFUNCPROC glDepthFunc;
PFNGLDEPTHMASKPROC glDepthMask;
PFNGLDEPTHRANGEFPROC glDepthRangef;
PFNGLDETACHSHADERPROC glDetachShader;
PFNGLDISABLEPROC glDisable;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
PFNGLDRAWARRAYSPROC glDrawArrays;
PFNGLDRAWELEMENTSPROC glDrawElements;
PFNGLENABLEPROC glEnable;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
PFNGLFINISHPROC glFinish;
PFNGLFLUSHPROC glFlush;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
PFNGLFRONTFACEPROC glFrontFace;
PFNGLGENBUFFERSPROC glGenBuffers;
PFNGLGENERATEMIPMAPPROC glGenerateMipMap;
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;
PFNGLGENTEXTURESPROC glGenTextures;
PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib;
PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform;
PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;
PFNGLGETBOOLEANVPROC getBooleanv;
PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;
PFNGLGETERRORPROC glGetError;
PFNGLGETFLOATVPROC glGetFloatv;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv;
PFNGLGETINTEGERVPROC glGetIntegerv;
PFNGLGETPROGRAMIVPROC glGetProgramiv;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv;
PFNGLGETSHADERIVPROC glGetShaderiv;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
PFNGLGETSHADERPRECISIONFORMATPROC glGetShaderPrecisionFormat;
PFNGLGETSHADERSOURCEPROC glGetShaderSource;
PFNGLGETSTRINGPROC glGetString;
PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv;
PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv;
PFNGLGETUNIFORMFVPROC glGetUniformfv;
PFNGLGETUNIFORMIVPROC glGetUniformiv;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv;
PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv;
PFNGLGETVERTEXATTRIBPOINTERVPROC getVertexAttribPointer;
PFNGLHINTPROC glHint;
PFNGLISBUFFERPROC glIsBuffer;
PFNGLISENABLEDPROC glIsEnabled;
PFNGLISFRAMEBUFFERPROC glIsFramebuffer;
PFNGLISPROGRAMPROC glIsProgram;
PFNGLISRENDERBUFFERPROC glIsRenderbuffer;
PFNGLISSHADERPROC glIsShader;
PFNGLISTEXTUREPROC glIsTexture;
PFNGLLINEWIDTHPROC glLineWidth;
PFNGLLINKPROGRAMPROC glLinkProgram;
PFNGLPIXELSTOREIPROC glPixelStorei;
PFNGLPOLYGONOFFSETPROC glPolygonOffset;
PFNGLREADPIXELSPROC glReadPixels;
PFNGLRELEASESHADERCOMPILERPROC glReleaseShaderCompiler;
PFNGLRENDERBUFFERSTORAGEPROC glRenderBufferStorage;
PFNGLSAMPLECOVERAGEPROC glSampleCoverage;
PFNGLSCISSORPROC glScissor;
PFNGLSHADERBINARYPROC glShaderBinary;
PFNGLSHADERSOURCEPROC glShaderSource;
PFNGLSTENCILFUNCPROC glStencilFunc;
PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate;
PFNGLSTENCILMASKPROC glStencilMask;
PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate;
PFNGLSTENCILOPPROC glStencilOp;
PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate;
PFNGLTEXIMAGE2DPROC glTexImage2D;
PFNGLTEXPARAMETERFPROC glTexParameterf;
PFNGLTEXPARAMETERFVPROC glTexParameterfv;
PFNGLTEXPARAMETERIPROC glTexParameteri;
PFNGLTEXPARAMETERIVPROC glTexParameteriv;
PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D;
PFNGLUNIFORM1FPROC glUniform1f;
PFNGLUNIFORM1FVPROC glUniform1fv;
PFNGLUNIFORM1IPROC glUniform1i;
PFNGLUNIFORM1IVPROC glUniform1iv;
PFNGLUNIFORM2FPROC glUniform2f;
PFNGLUNIFORM2FVPROC glUniform2fv;
PFNGLUNIFORM2IPROC glUniform2i;
PFNGLUNIFORM2IVPROC glUniform2iv;
PFNGLUNIFORM3FPROC glUniform3f;
PFNGLUNIFORM3FVPROC glUniform3fv;
PFNGLUNIFORM3IPROC glUniform3i;
PFNGLUNIFORM3IVPROC glUniform3iv;
PFNGLUNIFORM4FPROC glUniform4f;
PFNGLUNIFORM4FVPROC glUniform4fv;
PFNGLUNIFORM4IPROC glUniform4i;
PFNGLUNIFORM4IVPROC glUniform4iv;
PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
PFNGLUSEPROGRAMPROC glUseProgram;
PFNGLVALIDATEPROGRAMPROC glValidateProgram;
PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f;
PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv;
PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f;
PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv;
PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f;
PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv;
PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f;
PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
PFNGLVIEWPORTPROC glViewport;

void loadGLFunctions(void* (*loader)(const char*)) {
	glActiveTexture = (PFNGLACTIVETEXTUREPROC)loader("glActiveTexture");
	glAttachShader = (PFNGLATTACHSHADERPROC)loader("glAttachShader");
	glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC)loader("glBindAttribLocation");
	glBindBuffer = (PFNGLBINDBUFFERPROC)loader("glBindBuffer");
	glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC)loader("glBindFramebuffer");
	glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC)loader("glBindRenderbuffer");
	glBindTexture = (PFNGLBINDTEXTUREPROC)loader("glBindTexture");
	glBlendColor = (PFNGLBLENDCOLORPROC)loader("glBlendColor");
	glBlendEquation = (PFNGLBLENDEQUATIONPROC)loader("glBlendEquation");
	glBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC)loader("glBlendEquationSeparate");
	glBlendFunc = (PFNGLBLENDFUNCPROC)loader("glBlendFunc");
	glBlendFuncSeparate = (PFNGLBLENDFUNCSEPARATEPROC)loader("glBlendFuncSeparate");
	glBufferData = (PFNGLBUFFERDATAPROC)loader("glBufferData");
	glBufferSubData = (PFNGLBUFFERSUBDATAPROC)loader("glBufferSubData");
	glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)loader("glCheckFramebufferStatus");
	glClear = (PFNGLCLEARPROC)loader("glClear");
	glClearColor = (PFNGLCLEARCOLORPROC)loader("glClearColor");
	glClearDepth = (PFNGLCLEARDEPTHFPROC)loader("glClearDepth");
	glClearStencil = (PFNGLCLEARSTENCILPROC)loader("glClearStencil");
	glColorMask = (PFNGLCOLORMASKPROC)loader("glColorMask");
	glCompileShader = (PFNGLCOMPILESHADERPROC)loader("glCompileShader");
	glCompressedTexImage2D = (PFNGLCOMPRESSEDTEXIMAGE2DPROC)loader("glCompressedTexImage2D");
	glCompressedTexSubImage2D = (PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC)loader("glCompressedTexSubImage2D");
	glCopyTexImage2D = (PFNGLCOPYTEXIMAGE2DPROC)loader("glCopyTexImage2D");
	glCopyTexSubImage2D = (PFNGLCOPYTEXSUBIMAGE2DPROC)loader("glCopyTexSubImage2D");
	glCreateProgram = (PFNGLCREATEPROGRAMPROC)loader("glCreateProgram");
	glCreateShader = (PFNGLCREATESHADERPROC)loader("glCreateShader");
	glCullFace = (PFNGLCULLFACEPROC)loader("glCullFace");
	glDeleteBuffers = (PFNGLDELETEBUFFERSPROC)loader("glDeleteBuffers");
	glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC)loader("glDeleteFramebuffers");
	glDeleteProgram = (PFNGLDELETEPROGRAMPROC)loader("glDeleteProgram");
	glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC)loader("glDeleteRenderbuffers");
	glDeleteShader = (PFNGLDELETESHADERPROC)loader("glDeleteShader");
	glDeleteTextures = (PFNGLDELETETEXTURESPROC)loader("glDeleteTextures");
	glDepthFunc = (PFNGLDEPTHFUNCPROC)loader("glDepthFunc");
	glDepthMask = (PFNGLDEPTHMASKPROC)loader("glDepthMask");
	glDepthRangef = (PFNGLDEPTHRANGEFPROC)loader("glDepthRangef");
	glDetachShader = (PFNGLDETACHSHADERPROC)loader("glDetachShader");
	glDisable = (PFNGLDISABLEPROC)loader("glDisable");
	glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC)loader("glDisableVertexAttribArray");
	glDrawArrays = (PFNGLDRAWARRAYSPROC)loader("glDrawArrays");
	glDrawElements = (PFNGLDRAWELEMENTSPROC)loader("glDrawElements");
	glEnable = (PFNGLENABLEPROC)loader("glEnable");
	glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC)loader("glEnableVertexAttribArray");
	glFinish = (PFNGLFINISHPROC)loader("glFinish");
	glFlush = (PFNGLFLUSHPROC)loader("glFlush");
	glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)loader("glFramebufferRenderbuffer");
	glFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC)loader("glFramebufferTexture2D");
	glFrontFace = (PFNGLFRONTFACEPROC)loader("glFrontFace");
	glGenBuffers = (PFNGLGENBUFFERSPROC)loader("glGenBuffers");
	glGenerateMipMap = (PFNGLGENERATEMIPMAPPROC)loader("glGenerateMipMap");
	glGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC)loader("glGenFramebuffers");
	glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC)loader("glGenRenderbuffers");
	glGenTextures = (PFNGLGENTEXTURESPROC)loader("glGenTextures");
	glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC)loader("glGetActiveAttrib");
	glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC)loader("glGetActiveUniform");
	glGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC)loader("glGetAttachedShaders");
	glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC)loader("glGetAttribLocation");
	getBooleanv = (PFNGLGETBOOLEANVPROC)loader("getBooleanv");
	glGetBufferParameteriv = (PFNGLGETBUFFERPARAMETERIVPROC)loader("glGetBufferParameteriv");
	glGetError = (PFNGLGETERRORPROC)loader("glGetError");
	glGetFloatv = (PFNGLGETFLOATVPROC)loader("glGetFloatv");
	glGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)loader("glGetFramebufferAttachmentParameteriv");
	glGetIntegerv = (PFNGLGETINTEGERVPROC)loader("glGetIntegerv");
	glGetProgramiv = (PFNGLGETPROGRAMIVPROC)loader("glGetProgramiv");
	glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC)loader("glGetProgramInfoLog");
	glGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC)loader("glGetRenderbufferParameteriv");
	glGetShaderiv = (PFNGLGETSHADERIVPROC)loader("glGetShaderiv");
	glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)loader("glGetShaderInfoLog");
	glGetShaderPrecisionFormat = (PFNGLGETSHADERPRECISIONFORMATPROC)loader("glGetShaderPrecisionFormat");
	glGetShaderSource = (PFNGLGETSHADERSOURCEPROC)loader("glGetShaderSource");
	glGetString = (PFNGLGETSTRINGPROC)loader("glGetString");
	glGetTexParameterfv = (PFNGLGETTEXPARAMETERFVPROC)loader("glGetTexParameterfv");
	glGetTexParameteriv = (PFNGLGETTEXPARAMETERIVPROC)loader("glGetTexParameteriv");
	glGetUniformfv = (PFNGLGETUNIFORMFVPROC)loader("glGetUniformfv");
	glGetUniformiv = (PFNGLGETUNIFORMIVPROC)loader("glGetUniformiv");
	glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC)loader("glGetUniformLocation");
	glGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC)loader("glGetVertexAttribfv");
	glGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC)loader("glGetVertexAttribiv");
	getVertexAttribPointer = (PFNGLGETVERTEXATTRIBPOINTERVPROC)loader("getVertexAttribPointer");
	glHint = (PFNGLHINTPROC)loader("glHint");
	glIsBuffer = (PFNGLISBUFFERPROC)loader("glIsBuffer");
	glIsEnabled = (PFNGLISENABLEDPROC)loader("glIsEnabled");
	glIsFramebuffer = (PFNGLISFRAMEBUFFERPROC)loader("glIsFramebuffer");
	glIsProgram = (PFNGLISPROGRAMPROC)loader("glIsProgram");
	glIsRenderbuffer = (PFNGLISRENDERBUFFERPROC)loader("glIsRenderbuffer");
	glIsShader = (PFNGLISSHADERPROC)loader("glIsShader");
	glIsTexture = (PFNGLISTEXTUREPROC)loader("glIsTexture");
	glLineWidth = (PFNGLLINEWIDTHPROC)loader("glLineWidth");
	glLinkProgram = (PFNGLLINKPROGRAMPROC)loader("glLinkProgram");
	glPixelStorei = (PFNGLPIXELSTOREIPROC)loader("glPixelStorei");
	glPolygonOffset = (PFNGLPOLYGONOFFSETPROC)loader("glPolygonOffset");
	glReadPixels = (PFNGLREADPIXELSPROC)loader("glReadPixels");
	glReleaseShaderCompiler = (PFNGLRELEASESHADERCOMPILERPROC)loader("glReleaseShaderCompiler");
	glRenderBufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC)loader("glRenderBufferStorage");
	glSampleCoverage = (PFNGLSAMPLECOVERAGEPROC)loader("glSampleCoverage");
	glScissor = (PFNGLSCISSORPROC)loader("glScissor");
	glShaderBinary = (PFNGLSHADERBINARYPROC)loader("glShaderBinary");
	glShaderSource = (PFNGLSHADERSOURCEPROC)loader("glShaderSource");
	glStencilFunc = (PFNGLSTENCILFUNCPROC)loader("glStencilFunc");
	glStencilFuncSeparate = (PFNGLSTENCILFUNCSEPARATEPROC)loader("glStencilFuncSeparate");
	glStencilMask = (PFNGLSTENCILMASKPROC)loader("glStencilMask");
	glStencilMaskSeparate = (PFNGLSTENCILMASKSEPARATEPROC)loader("glStencilMaskSeparate");
	glStencilOp = (PFNGLSTENCILOPPROC)loader("glStencilOp");
	glStencilOpSeparate = (PFNGLSTENCILOPSEPARATEPROC)loader("glStencilOpSeparate");
	glTexImage2D = (PFNGLTEXIMAGE2DPROC)loader("glTexImage2D");
	glTexParameterf = (PFNGLTEXPARAMETERFPROC)loader("glTexParameterf");
	glTexParameterfv = (PFNGLTEXPARAMETERFVPROC)loader("glTexParameterfv");
	glTexParameteri = (PFNGLTEXPARAMETERIPROC)loader("glTexParameteri");
	glTexParameteriv = (PFNGLTEXPARAMETERIVPROC)loader("glTexParameteriv");
	glTexSubImage2D = (PFNGLTEXSUBIMAGE2DPROC)loader("glTexSubImage2D");
	glUniform1f = (PFNGLUNIFORM1FPROC)loader("glUniform1f");
	glUniform1fv = (PFNGLUNIFORM1FVPROC)loader("glUniform1fv");
	glUniform1i = (PFNGLUNIFORM1IPROC)loader("glUniform1i");
	glUniform1iv = (PFNGLUNIFORM1IVPROC)loader("glUniform1iv");
	glUniform2f = (PFNGLUNIFORM2FPROC)loader("glUniform2f");
	glUniform2fv = (PFNGLUNIFORM2FVPROC)loader("glUniform2fv");
	glUniform2i = (PFNGLUNIFORM2IPROC)loader("glUniform2i");
	glUniform2iv = (PFNGLUNIFORM2IVPROC)loader("glUniform2iv");
	glUniform3f = (PFNGLUNIFORM3FPROC)loader("glUniform3f");
	glUniform3fv = (PFNGLUNIFORM3FVPROC)loader("glUniform3fv");
	glUniform3i = (PFNGLUNIFORM3IPROC)loader("glUniform3i");
	glUniform3iv = (PFNGLUNIFORM3IVPROC)loader("glUniform3iv");
	glUniform4f = (PFNGLUNIFORM4FPROC)loader("glUniform4f");
	glUniform4fv = (PFNGLUNIFORM4FVPROC)loader("glUniform4fv");
	glUniform4i = (PFNGLUNIFORM4IPROC)loader("glUniform4i");
	glUniform4iv = (PFNGLUNIFORM4IVPROC)loader("glUniform4iv");
	glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC)loader("glUniformMatrix2fv");
	glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC)loader("glUniformMatrix3fv");
	glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)loader("glUniformMatrix4fv");
	glUseProgram = (PFNGLUSEPROGRAMPROC)loader("glUseProgram");
	glValidateProgram = (PFNGLVALIDATEPROGRAMPROC)loader("glValidateProgram");
	glVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC)loader("glVertexAttrib1f");
	glVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC)loader("glVertexAttrib1fv");
	glVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC)loader("glVertexAttrib2f");
	glVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC)loader("glVertexAttrib2fv");
	glVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC)loader("glVertexAttrib3f");
	glVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC)loader("glVertexAttrib3fv");
	glVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC)loader("glVertexAttrib4f");
	glVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC)loader("glVertexAttrib4fv");
	glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC)loader("glVertexAttribPointer");
	glViewport = (PFNGLVIEWPORTPROC)loader("glViewport");
}